### ISSUE TITLE
Offer :latest tag

### ISSUE THREAD

**Issue by oscartbeaumont** [devture/exim-relay#14]
It would be great if a `latest` tag was provided for this image. I understand that `latest` is not recommended in production but I am using this image on a personal deployment for sending email alerts. I would rather get security updates automatically and deal with the risk that during an update something breaks than miss a security update.

Thanks for the image!

**Comment by spantaleev** [comment]
I see! I've pushed `:latest`. Now I just need to remember to keep it updated ;)

.. and it needs to be pulled often-enough to prevent Docker Hub from auto-deleting it.

**Comment by oscartbeaumont** [comment]
Could GitHub Actions not be used for that purpose? I would be happy to help set it up if you wanted to pursue that route.

Otherwise, Thanks for your help.

**Comment by spantaleev** [comment]
It probably could, but I haven't looked into Github Actions or thought about what a good flow would be for this repository.

If you'd like to take a stab at it, that'd be nice!
