### ISSUE TITLE
Manifest missing

### ISSUE THREAD

**Issue by jakesylvestre** [devture/exim-relay#4]
Hi,

It'd also appread the image is missing:

```
 % docker pull devture/exim-relay:4.93.1-r0

Error response from daemon: manifest for devture/exim-relay:4.93.1-r0 not found: manifest unknown: manifest unknown
```

The manifest appears to be missing on all tags

**Comment by spantaleev** [comment]
We had `4.93.1-r0` for some time, but that was confusing, as there is no such Exim version (yet).

I think I had rebuilt the `4.93` version and had tagged it incorrectly as `.1` before. I've removed that tag at some point, to avoid causing confusion (even though it did cause some breakage similar to what you're reporting here now).

The latest tag we currently have for the Docker image is `4.93-r1`.

See all the available tags here: https://hub.docker.com/r/devture/exim-relay/tags
