### ISSUE TITLE
Kubernetes compatibility

### ISSUE THREAD

**Issue by zedtux** [devture/exim-relay#6]
As par [this SO question](https://stackoverflow.com/questions/50803268/kubernetes-equivalent-of-docker-run-init), the `--init` flag and `init` docker-compose key are unknown from Kubernetes.

It would be great to have Tini included in this image, avoiding to use that `--init` flag, and making this image Kubernetes compatible.

**Comment by zedtux** [comment]
Awesome work @spantaleev 👌

**Comment by spantaleev** [comment]
Thanks!

Fixed and released as `docker.io/devture/exim-relay:4.94.2-r0`
